apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudprofile-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mohsin.ditinex.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudprofile-frontend-service
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cloudprofile-backend-service
                port:
                  number: 5001
